DROP TABLE IF EXISTS DE_TAB_SubjectLecturer;
DROP TABLE IF EXISTS DE_DOC_ExamMarks;
DROP TABLE IF EXISTS DE_CTL_Lecturers;
DROP TABLE IF EXISTS DE_CTL_Students;
DROP TABLE IF EXISTS DE_CTL_Subjects;
DROP TABLE IF EXISTS DE_CTL_Lecturers;
DROP TABLE IF EXISTS DE_CTL_Universities;
DROP TABLE IF EXISTS DE_CTL_Cities;